<?php
/**
 * WDS GROUP
 *
 * @name        footer.php
 * @category    WDS
 * @package        
 * @subpackage           
 * @author      Thuy Dinh Xuan <thuydx@wds.vn>
 * @copyright   Copyright (c)2008-2010 WDS GROUP. All rights reserved
 * @license     http://wds.vn/license/     WDS Software License
 * @version     $1.0$
 * 9:24:22 PM - 2011
 *
 * LICENSE
 *
 * This source file is copyrighted by WDS GROUP, full details in LICENSE.txt.
 * It is also available through the Internet at this URL:
 * http://wds.vn/license/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the Internet, please send an email
 * to license@wds.vn so we can send you a copy immediately.
 *
 */

?>
<footer id="footer_outer">
        	<div id="footer_wrapper">
                <aside id="footer_left">
                	<article class="footer_article">
                    	<div class="footer_column">
                       		<div class="footer_listing">
                                <h2 class="footer_title">Main Heading</h2>
                                <ul class="footer_link">
                                    <li>justo convallis luctus rutrum</li>
                                    <li>Erat nulla fermentum </li>
                                    <li>Diam, at nonummy quam  </li>
                                    <li>Ante ac quam.</li>
                                    <li>Maecenas urna purus</li>
                                    <li>Fermentum id, molestie in</li>
                                    <li>Porttitor, felis</li>							
                                </ul>
                            </div><!-- End .footer_listing -->
                        </div>
                        <div class="footer_column">
                       		<div class="footer_listing">
                                <h2 class="footer_title">Main Heading</h2>
                                <ul class="footer_link">
                                    <li>justo convallis luctus rutrum</li>
                                    <li>Erat nulla fermentum </li>
                                    <li>Diam, at nonummy quam  </li>
                                    <li>Ante ac quam.</li>
                                    <li>Maecenas urna purus</li>
                                    <li>Fermentum id, molestie in</li>
                                    <li>Porttitor, felis</li>							
                                </ul>
                            </div><!-- End .footer_listing -->
                        </div>
                        <div class="footer_column">
                       		<div class="footer_listing">
                                <h2 class="footer_title">Main Heading</h2>
                                <ul class="footer_link">
                                    <li>justo convallis luctus rutrum</li>
                                    <li>Erat nulla fermentum </li>
                                    <li>Diam, at nonummy quam  </li>  				
                                </ul>
                                <h2 class="footer_title">Main Heading</h2>
                                <ul class="footer_link">
                                    <li>Ante ac quam.</li>
                                    <li>Maecenas urna purus</li>
                                    <li>Fermentum id, molestie in</li>							
                                </ul>
                            </div><!-- End .footer_listing -->
                        </div>
                    </article>
                </aside>
                <aside id="footer_right">
                	<div class="footer_column1">
                        <div class="footer_listing">
                            <h2 class="footer_title">Contact Details</h2>
                            <ul class="footer_link">
                                <li>Name Company</li>
                                <li>Adress here 1</li>
                                <li>Adress here 2</li>							
                            </ul>
                        </div><!-- End .footer_listing -->
                    </div>
                    <div class="footer_column2">
                        <div class="footer_listing">
                            <ul class="footer_link">
                                <li>Tel: 1234 567 890</li>
                                <li>Fax 1234 567 890</li>
                                <li>info@wds.vn</li>							
                            </ul>
                            <ul class="footer_link">
                                <li>Tel: 1234 567 890</li>
                                <li>Office Hours: 9:00am - 5:30pm</li>							
                            </ul>
                        </div><!-- End .footer_listing -->
                    </div>
                </aside>
        	</div>
            <div class="clearfix"></div>
            <div id="footer_bar">
            	<article id="copyright">
       			<p>
                    Copyright © 2011 WDS GROUP.
                    
				</p>	
                </article>
            </div>
        </footer>