<?php

/**
 * WDS GROUP
 *
 * @name        footer.phtml
 * @category    Templates
 * @package    	Admincp
 * @subpackage  Layouts    
 * @author      Thuy Dinh Xuan <thuydx@wds.vn>
 * @copyright   Copyright (c)2008-2010 WDS GROUP. All rights reserved
 * @license     http://wds.vn/license/     WDS Software License
 * @version     $1.0$
 * 10:05:15 PM - May 15, 2011
 *
 * LICENSE
 *
 * This source file is copyrighted by WDS GROUP, full details in LICENSE.txt.
 * It is also available through the Internet at this URL:
 * http://wds.vn/license/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the Internet, please send an email
 * to license@wds.vn so we can send you a copy immediately.
 *
 */
?>

        <div class="grid_12"><center>
            Copyright &copy; 2011. Theme by <a target="_blank" href="http://wds.vn">WDS Design</a></center>
        </div>