
    <div id="wrapper">
        <header>
            <h1><a href="http://wds.vn/">WDS-CMS Admin</a></h1>
            <nav>
				<ul id="main-navigation" class="clearfix"> 
					<li class="dropdown active"> 
						<a href="#a">active item</a> 
						<ul> 
							<li> 
								<a href="#aa">menu item</a> 
							</li> 
							<li class="dropdown"> 
								<a href="#ab">menu item</a> 
								<ul> 
									<li class="current"><a href="#">menu item</a></li> 
									<li><a href="#aba">menu item</a></li> 
									<li><a href="#abb">menu item</a></li> 
									<li><a href="#abc">menu item</a></li> 
									<li><a href="#abd">menu item</a></li> 
								</ul> 
							</li> 
							<li class="dropdown"> 
								<a href="#">menu item</a> 
								<ul> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
								</ul> 
							</li> 
							<li class="dropdown"> 
								<a href="#">menu item</a> 
								<ul> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
								</ul> 
							</li> 
						</ul> 
					</li> 
					<li> 
						<a href="#">menu item</a> 
					</li> 
					<li class="dropdown"> 
						<a href="#">menu item</a> 
						<ul> 
							<li class="dropdown"> 
								<a href="#">menu item</a> 
								<ul> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
								</ul> 
							</li> 
							<li class="dropdown"> 
								<a href="#">menu item</a> 
								<ul> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
								</ul> 
							</li> 
							<li class="dropdown"> 
								<a href="#">menu item</a> 
								<ul> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
								</ul> 
							</li> 
							<li class="dropdown"> 
								<a href="#">menu item</a> 
								<ul> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
									<li><a href="#">menu item</a></li> 
								</ul>
							</li>
						</ul> 
					</li> 
                    <li class="fr dropdown"> 
                        <a href="#" class="with-profile-image"><span><img src="images/profile-image.png" /></span>Administrator</a> 
                        <ul>
                            <li><a href="#">Settings</a></li> 
                            <li><a href="#">Users</a></li> 
                            <li><a href="#">Groups</a></li> 
                            <li><a href="#">Signout</a></li> 
                        </ul> 
                    </li> 
				</ul> 
            </nav>
        </header>
        
        <section>
            <!-- Sidebar -->

            <aside>
                <nav>
					<h2>GROUP 1</h2>
                    <ul>
                        <li><a href="dashboard.html">Dashboard</a></li>
                        <li><a href="media.html">Media</a></li>
                        <li class="current"><a href="forms.html">Forms</a></li>
                        <li><a href="wizard.html">Wizard</a></li>
                        <li><a href="tables.html">Tables</a></li>
                    </ul>
                </nav>
                <nav>
                    <h2>GROUP 2</h2>
                    <ul>
                        <li><a href="calendar.html">Calendar</a></li>
                        <li><a href="wysiwyg.html">WYSIWYG Editor</a></li>
                    </ul>
                </nav>
            </aside>

            <!-- Sidebar End -->

            <section>
                <header class="container_12 clearfix">
                    <div class="grid_12">
                        <h1>WYSIWYG Editor</h1>
                    </div>
                </header>
                <section class="container_12 clearfix">
                    <div class="portlet grid_12">
                        <header>
                            <h2>Form Sample 1</h2>
                        </header>
                        <section>
                            <form class="form has-validation">

                                <div class="clearfix">

                                    <label for="form-name" class="form-label">Name <em>*</em><small>Enter your name</small></label>

                                    <div class="form-input"><input type="text" id="form-name" name="name" required="required" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-email" class="form-label">Email <em>*</em><small>A valid email address</small></label>

                                    <div class="form-input"><input type="email" id="form-email" required="required" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-birthday" class="form-label">Birthdate<small>mm/dd/yyyy</small></label>

                                    <div class="form-input"><input type="date" id="form-birthday" name="date" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-username" class="form-label">Username <em>*</em><small>Alphanumeric (max 12 char.)</small></label>

                                    <div class="form-input"><input type="text" id="form-username" name="username" required="required" maxlength="12" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-password" class="form-label">Password<small>max. 30 char.</small></label>

                                    <div class="form-input"><input type="password" id="form-password" name="password" maxlength="30" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-password-check" class="form-label">Password check<small>Re-enter your password</small></label>

                                    <div class="form-input"><input type="password" id="form-password-check" name="check" data-equals="password" maxlength="30" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-website" class="form-label">Website <em>*</em><small>A valid URL</small></label>

                                    <div class="form-input"><input type="url" id="form-website" required="required" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-textarea" class="form-label">About you <em>*</em><small>Describe yourself</small></label>

                                    <div class="form-input form-textarea"><textarea id="form-textarea" required="required" rows="5"></textarea></div>

                                </div>
                                
                                <div class="clearfix">

                                    <label for="form-timezone" class="form-label">Timezone<small>Your timezone</small></label>

                                    <div class="form-input"><select id="form-timezone"><option>America/Los Angeles</option><option>America/New York</option><option>Asia/Manila</option></select></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-upload" class="form-label">Photo<small>80x80 jpeg/png format</small></label>

                                    <div class="form-input"><input type="file" id="form-upload" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-gender" class="form-label">Gender<small>Male or female?</small></label>

                                    <div class="form-input"><label><input type="radio" name="gender" id="form-gender" value="male" /> Male</label> <label><input type="radio" name="gender" value="female" /> Female</label></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form-updates" class="form-label">Receive Updates?<small>Receive weekly updates</small></label>

                                    <div class="form-input"><input type="checkbox" id="form-updates" value="1" /></div>

                                </div>

                                <div class="form-action clearfix">

                                    <button class="button" type="submit" data-icon-primary="ui-icon-circle-check">OK</button>

                                    <button class="button" type="reset">Reset</button>

                                </div>

                            </form>
                        </section>
                    </div>
                    <div class="portlet grid_12 leading">
                        <header>
                            <h2>Form Sample 2</h2>
                        </header>
                        <section>
                            <form class="form has-validation">

                                <div class="clearfix">

                                    <label for="form2-name" class="form-label no-description">Name <em>*</em><small>Enter your name</small></label>

                                    <div class="form-input"><input type="text" id="form2-name" name="name" required="required" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-email" class="form-label no-description">Email <em>*</em><small>A valid email address</small></label>

                                    <div class="form-input"><input type="email" id="form2-email" required="required" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-birthday" class="form-label no-description">Birthdate<small>mm/dd/yyyy</small></label>

                                    <div class="form-input"><input type="date" id="form2-birthday" name="date" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-username" class="form-label no-description">Username <em>*</em><small>Alphanumeric (max 12 char.)</small></label>

                                    <div class="form-input"><input type="text" id="form2-username" name="username" required="required" maxlength="12" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-password" class="form-label no-description">Password<small>max. 30 char.</small></label>

                                    <div class="form-input"><input type="password" id="form2-password" name="password" maxlength="30" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-password-check" class="form-label no-description">Password check<small>Re-enter your password</small></label>

                                    <div class="form-input"><input type="password" id="form2-password-check" name="check" data-equals="password" maxlength="30" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-website" class="form-label no-description">Website <em>*</em><small>A valid URL</small></label>

                                    <div class="form-input"><input type="url" id="form2-website" required="required" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-textarea" class="form-label">About you <em>*</em><small>Describe yourself</small></label>

                                    <div class="form-input form-textarea"><textarea id="form2-textarea" required="required" rows="5"></textarea></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-timezone" class="form-label no-description">Timezone<small>Your timezone</small></label>

                                    <div class="form-input"><select id="form2-timezone"><option>America/Los Angeles</option><option>America/New York</option><option>Asia/Manila</option></select></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-upload" class="form-label no-description">Photo<small>80x80 jpeg/png format</small></label>

                                    <div class="form-input"><input type="file" id="form2-upload" /></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-gender" class="form-label no-description">Gender<small>Male or female?</small></label>

                                    <div class="form-input"><label><input type="radio" name="gender" id="form2-gender" value="male" /> Male</label> <label><input type="radio" name="gender" value="female" /> Female</label></div>

                                </div>

                                <div class="clearfix">

                                    <label for="form2-updates" class="form-label no-description">Receive Updates?<small>Receive weekly updates</small></label>

                                    <div class="form-input"><input type="checkbox" id="form2-updates" value="1" /></div>

                                </div>

                                <div class="form-action clearfix">

                                    <button class="button" type="submit" data-icon-primary="ui-icon-circle-check">OK</button>

                                    <button class="button" type="reset">Reset</button>

                                </div>

                            </form>
                        </section>
                    </div>
                </section>
                <footer class="container_12 clearfix">
                    <div class="grid_12"><center>
                        Copyright &copy; 2011. Theme by <a target="_blank" href="http://wds.vn">WDS Design</a></center>
                    </div>
                </footer>
            </section>

            <!-- Main Section End -->
        </section>
    </div>
    
    <!-- MAIN JAVASCRIPTS -->
    <script src="../../ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.js"></script>
    <script>window.jQuery || document.write("<script src='js/jquery.min.js'>\x3C/script>")</script>
    <script type="text/javascript" src="js/jquery.tools.min.js"></script>
    <script type="text/javascript" src="js/jquery.uniform.min.js"></script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="js/PIE.js"></script>
    <script type="text/javascript" src="js/ie.js"></script>
    <![endif]-->

    <script type="text/javascript" src="js/global.js"></script>
    <!-- MAIN JAVASCRIPTS END -->

    <!-- LOADING SCRIPT -->
    <script>
    $(window).load(function(){
        $("#loading").fadeOut(function(){
            $(this).remove();
            $('body').removeAttr('style');
        });
    });
    </script>
    <!-- LOADING SCRIPT -->

