<?php

/**
 * WDS GROUP
 *
 * @name        leftcolumn.phtml
 * @category    Templates
 * @package    	Admincp
 * @subpackage	Layout    
 * @author      Thuy Dinh Xuan <thuydx@wds.vn>
 * @copyright   Copyright (c)2008-2010 WDS GROUP. All rights reserved
 * @license     http://wds.vn/license/     WDS Software License
 * @version     $1.0$
 * 9:59:25 PM - May 15, 2011
 *
 * LICENSE
 *
 * This source file is copyrighted by WDS GROUP, full details in LICENSE.txt.
 * It is also available through the Internet at this URL:
 * http://wds.vn/license/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the Internet, please send an email
 * to license@wds.vn so we can send you a copy immediately.
 *
 */
 
?>
				<nav>
                    <h2>Tin Tức</h2>
                    <ul>
                        <li><a href="#">Thêm Tin Tức</a></li>
                        <li><a href="#">Danh Sách Tin Tức</a></li>
                    </ul>
                </nav>
				<nav>
				     <h2>Sản Phẩm</h2>
                    <ul>
                        <li><a href="#">Thêm Sản Phẩm</a></li>
                        <li><a href="#">Danh Sách Sản Phẩm</a></li>
                    </ul>
                </nav>
                <nav>
                    <h2>Giới thiệu</h2>
                    <ul>
                        <li><a href="#">Bài Giới Thiệu</a></li>
                    </ul>
                </nav>
                <nav>
                    <h2>Người Dùng</h2>
                    <ul>
                        <li><a href="#">Thêm Người Dùng</a></li>
                        <li><a href="#">Danh Sách Người Dùng</a></li>
                    </ul>
                </nav>
                <nav>
                    <h2>Liên Hệ</h2>
                    <ul>
                        <li><a href="#">Thêm Địa Chỉ Liên Hệ</a></li>
                        <li><a href="#">Danh Sách Địa Chỉ Liên Hệ</a></li>
                    </ul>
                </nav>                                